[2017-10-16 16:22:25] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-16 16:23:07] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-16 16:23:07] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-10-16 16:23:12] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"aa7c97","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/aa7c97","method":"GET"} []
[2017-10-16 17:28:10] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-16 17:28:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-10-16 17:28:15] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"2b5be2","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/2b5be2","method":"GET"} []
[2017-10-17 12:10:15] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "Bundle "AcmeApiBundle" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file? in @AcmeApiBundle/Resources/config/routing.yml (which is being imported from "C:\wamp\www\comptabli/app/config\routing.yml"). Make sure the "AcmeApiBundle/Resources/config/routing.yml" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@AcmeApiBundle/Resources/config/routing.yml" is not empty." at C:\wamp\www\comptabli\vendor\symfony\symfony\src\Symfony\Component\Config\Loader\FileLoader.php line 177 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): Bundle \"AcmeApiBundle\" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file? in @AcmeApiBundle/Resources/config/routing.yml (which is being imported from \"C:\\wamp\\www\\comptabli/app/config\\routing.yml\"). Make sure the \"AcmeApiBundle/Resources/config/routing.yml\" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path \"@AcmeApiBundle/Resources/config/routing.yml\" is not empty. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Config\\Loader\\FileLoader.php:177, InvalidArgumentException(code: 0): Bundle \"AcmeApiBundle\" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file? at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Kernel.php:196)"} []
[2017-10-17 12:10:25] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-17 12:10:59] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-17 12:11:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-10-17 12:11:03] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"8872ea","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/8872ea","method":"GET"} []
[2017-10-17 15:48:15] php.DEBUG: Warning: unlink(web/bundles/nelmioapidoc): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\Filesystem\\\\Filesystem.php\",\"line\":183,\"trace\":[{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\FrameworkBundle\\\\Command\\\\AssetsInstallCommand.php\",\"line\":141,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-17 15:48:15] php.DEBUG: Warning: symlink(): Could not fetch file information(error 3) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\Filesystem\\\\Filesystem.php\",\"line\":348,\"trace\":[{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\FrameworkBundle\\\\Command\\\\AssetsInstallCommand.php\",\"line\":242,\"function\":\"symlink\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-17 15:48:15] php.DEBUG: Warning: symlink(): Cannot create symlink, error code(1314) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\Filesystem\\\\Filesystem.php\",\"line\":348,\"trace\":[{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\FrameworkBundle\\\\Command\\\\AssetsInstallCommand.php\",\"line\":242,\"function\":\"symlink\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-17 15:49:21] php.CRITICAL: Fatal Error: Class 'FOS\UserBundle\Entity\User' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Class 'FOS\\UserBundle\\Entity\\User' not found at C:\\wamp\\www\\comptabli\\src\\ApiBundle\\Entity\\User.php:16)"} []
[2017-10-17 15:50:27] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-17 15:50:27] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-10-17 15:50:31] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"0fa26e","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/0fa26e","method":"GET"} []
[2017-10-17 15:52:41] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-10-17 15:52:41] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-10-17 15:52:41] doctrine.DEBUG: CREATE TABLE oauth2_access_tokens (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_D247A21B5F37A13B (token), INDEX IDX_D247A21B19EB6921 (client_id), INDEX IDX_D247A21BA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-10-17 15:52:43] doctrine.DEBUG: CREATE TABLE oauth2_auth_codes (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, redirect_uri LONGTEXT NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_A018A10D5F37A13B (token), INDEX IDX_A018A10D19EB6921 (client_id), INDEX IDX_A018A10DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-10-17 15:52:45] doctrine.DEBUG: CREATE TABLE oauth2_clients (id INT AUTO_INCREMENT NOT NULL, random_id VARCHAR(255) NOT NULL, redirect_uris LONGTEXT NOT NULL COMMENT '(DC2Type:array)', secret VARCHAR(255) NOT NULL, allowed_grant_types LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-10-17 15:52:45] doctrine.DEBUG: CREATE TABLE oauth2_refresh_tokens (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_D394478C5F37A13B (token), INDEX IDX_D394478C19EB6921 (client_id), INDEX IDX_D394478CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-10-17 15:52:45] doctrine.DEBUG: CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_1483A5E992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_1483A5E9A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_1483A5E9C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-10-17 15:52:46] doctrine.DEBUG: ALTER TABLE oauth2_access_tokens ADD CONSTRAINT FK_D247A21B19EB6921 FOREIGN KEY (client_id) REFERENCES oauth2_clients (id) [] []
[2017-10-17 15:52:48] doctrine.DEBUG: ALTER TABLE oauth2_access_tokens ADD CONSTRAINT FK_D247A21BA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) [] []
[2017-10-17 15:52:48] doctrine.DEBUG: ALTER TABLE oauth2_auth_codes ADD CONSTRAINT FK_A018A10D19EB6921 FOREIGN KEY (client_id) REFERENCES oauth2_clients (id) [] []
[2017-10-17 15:52:49] doctrine.DEBUG: ALTER TABLE oauth2_auth_codes ADD CONSTRAINT FK_A018A10DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) [] []
[2017-10-17 15:52:50] doctrine.DEBUG: ALTER TABLE oauth2_refresh_tokens ADD CONSTRAINT FK_D394478C19EB6921 FOREIGN KEY (client_id) REFERENCES oauth2_clients (id) [] []
[2017-10-17 15:52:51] doctrine.DEBUG: ALTER TABLE oauth2_refresh_tokens ADD CONSTRAINT FK_D394478CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) [] []
[2017-10-17 15:55:47] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 15:55:48] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 16:48:12] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 16:48:12] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 16:50:06] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 16:50:06] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 16:51:43] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 16:51:43] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 16:53:41] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 16:53:41] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 16:55:25] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 16:55:25] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 16:57:12] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 16:57:12] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 16:59:01] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 16:59:01] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 17:10:45] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 17:10:45] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 17:14:00] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 17:14:00] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 17:16:15] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 17:16:16] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 17:18:38] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 17:18:38] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-17 17:24:16] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-17 17:24:16] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-18 09:47:42] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-18 09:47:42] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-10-18 09:47:53] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"210ae7","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/210ae7","method":"GET"} []
[2017-10-18 10:21:24] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-18 10:21:24] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-18 10:25:20] console.ERROR: Error thrown while running command "fos:user:create". Message: "No encoder has been configured for account "ApiBundle\Entity\User"." {"error":"[object] (RuntimeException(code: 0): No encoder has been configured for account \"ApiBundle\\Entity\\User\". at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\Encoder\\EncoderFactory.php:51)","command":"fos:user:create","message":"No encoder has been configured for account \"ApiBundle\\Entity\\User\"."} []
[2017-10-18 10:25:20] console.DEBUG: Command "fos:user:create" exited with code "1" {"command":"fos:user:create","code":1} []
[2017-10-18 10:34:24] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-18 10:34:24] doctrine.DEBUG: INSERT INTO users (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {"1":"admin","2":"admin","3":"admin@example.com","4":"admin@example.com","5":true,"6":"q3RCSE/IvsKT9PdLVSFmw62Mly [...]","7":"iEFWoNqCWX0H5KUOq7kPjJbRcd [...]","8":null,"9":null,"10":null,"11":[]} []
[2017-10-18 10:34:24] doctrine.DEBUG: "COMMIT" [] []
[2017-10-18 10:43:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 10:44:02] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 10:44:02] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 10:44:02] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 10:44:05] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:26:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 11:26:08] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:26:08] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 11:26:08] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 11:26:17] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:31] request.INFO: Matched route "_profiler". {"route":"_profiler","route_parameters":{"_controller":"web_profiler.controller.profiler:panelAction","token":"210ae7","_route":"_profiler"},"request_uri":"http://127.0.0.1:8000/_profiler/210ae7?panel=request","method":"GET"} []
[2017-10-18 11:43:32] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:35] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:36] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:45] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:46] request.INFO: Matched route "_profiler". {"route":"_profiler","route_parameters":{"_controller":"web_profiler.controller.profiler:panelAction","token":"210ae7","_route":"_profiler"},"request_uri":"http://127.0.0.1:8000/_profiler/210ae7?panel=request","method":"GET"} []
[2017-10-18 11:43:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:50] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:51] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:43:51] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:44:01] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:44:39] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-18 11:44:40] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:44:44] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:44:45] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:44:45] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 11:44:54] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:10:11] console.ERROR: Error thrown while running command "cache:clear --no-wrap --env=dev". Message: "The "--no-wrap" option does not exist." {"error":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--no-wrap\" option does not exist. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Input\\ArgvInput.php:222)","command":"cache:clear --no-wrap --env=dev","message":"The \"--no-wrap\" option does not exist."} []
[2017-10-18 12:10:11] console.DEBUG: Command "cache:clear --no-wrap --env=dev" exited with code "1" {"command":"cache:clear --no-wrap --env=dev","code":1} []
[2017-10-18 12:11:19] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:11:26] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:11:26] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:11:27] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:11:29] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:11:35] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:11:37] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:11:37] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:11:37] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:11:39] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:12:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:12:09] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:12:10] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:12:10] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:12:18] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:13:25] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-18 12:13:25] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:13:29] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:13:29] php.CRITICAL: Uncaught Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:13:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:13:37] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given, called in C:\wamp\www\comptabli\var\cache\dev\appDevDebugProjectContainer.php on line 2009 and defined at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 80) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 5 passed to FOS\\OAuthServerBundle\\Storage\\OAuthStorage::__construct() must implement interface Symfony\\Component\\Security\\Core\\User\\UserProviderInterface, instance of FOS\\UserBundle\\Doctrine\\UserManager given, called in C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2009 and defined at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:80)"} []
[2017-10-18 12:20:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:20:13] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-18 12:21:04] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-18 12:21:05] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-18 12:21:05] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-18 12:24:36] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /oauth/v2/token%20/%20grant_type=password%20/%20client_id=1_3bcbxd9e24g0gk4swg0kwgcwg4o8k8g4g888kwc44gcc0gwwk4%20/%20client_secret=4ok2x70rlfokc8g0wws8c8kwcokw80k44sg48goc0ok4w0so0k%20/%20username=admin%20/%20password=admin"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /oauth/v2/token%20/%20grant_type=password%20/%20client_id=1_3bcbxd9e24g0gk4swg0kwgcwg4o8k8g4g888kwc44gcc0gwwk4%20/%20client_secret=4ok2x70rlfokc8g0wws8c8kwcokw80k44sg48goc0ok4w0so0k%20/%20username=admin%20/%20password=admin\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-18 12:24:45] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-18 12:24:47] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"f102e0","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/f102e0","method":"GET"} []
[2017-10-18 12:24:48] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-18 12:24:48] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-18 12:27:40] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-18 15:45:47] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2017-10-18 15:45:51] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-18 15:45:51] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 12:32:49] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-23 12:32:51] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 12:32:51] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 12:34:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 12:34:11] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 12:34:13] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"9a8758","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/9a8758","method":"GET"} []
[2017-10-23 12:34:14] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 12:34:15] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 12:34:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 12:34:29] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 12:34:31] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"c85009","_route":"_wdt"},"request_uri":"http://localhost:8000/_wdt/c85009","method":"GET"} []
[2017-10-23 12:34:32] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 12:34:32] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 12:37:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 12:37:45] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 12:37:48] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"8f6d0f","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/8f6d0f","method":"GET"} []
[2017-10-23 12:37:49] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 12:37:49] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 12:46:22] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/app_dev.php/","method":"GET"} []
[2017-10-23 12:46:23] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 12:46:24] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 12:47:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links/"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links/\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 12:47:06] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 12:47:08] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"de7e27","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/de7e27","method":"GET"} []
[2017-10-23 12:47:09] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 12:47:09] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 12:48:04] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-23 12:48:04] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 12:48:04] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 13:10:40] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 13:10:45] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 13:15:41] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-23 13:15:42] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-23 13:15:42] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.username_canonical = ? LIMIT 1 ["admin"] []
[2017-10-23 13:15:43] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-23 13:15:43] doctrine.DEBUG: INSERT INTO oauth2_access_tokens (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"OThlMmY0ZDY2NDU2Yjg5MzU2Nm [...]","2":1508760943,"3":null,"4":1,"5":1} []
[2017-10-23 13:15:43] doctrine.DEBUG: "COMMIT" [] []
[2017-10-23 13:15:43] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-23 13:15:43] doctrine.DEBUG: INSERT INTO oauth2_refresh_tokens (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"NDJkN2M4ZGJiYjg1YzMxOTE3Yz [...]","2":1509966943,"3":null,"4":1,"5":1} []
[2017-10-23 13:15:43] doctrine.DEBUG: "COMMIT" [] []
[2017-10-23 13:19:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 13:19:57] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 13:20:28] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links%20%22Authorization:Bearer%20OThlMmY0ZDY2NDU2Yjg5MzU2NmYzZWMzY2RjZDdjZDRjZjFhY2M4Y2JmMzA3NTQ5MzkyMWNlMTIwMjk5MzRmMg"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links%20%22Authorization:Bearer%20OThlMmY0ZDY2NDU2Yjg5MzU2NmYzZWMzY2RjZDdjZDRjZjFhY2M4Y2JmMzA3NTQ5MzkyMWNlMTIwMjk5MzRmMg\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 13:20:34] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 13:20:36] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"1cb134","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/1cb134","method":"GET"} []
[2017-10-23 13:20:37] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 13:20:37] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 13:22:21] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 13:22:26] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 13:22:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links%20%22Authorization:Bearer%20OThlMmY0ZDY2NDU2Yjg5MzU2NmYzZWMzY2RjZDdjZDRjZjFhY2M4Y2JmMzA3NTQ5MzkyMWNlMTIwMjk5MzRmMg%22"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links%20%22Authorization:Bearer%20OThlMmY0ZDY2NDU2Yjg5MzU2NmYzZWMzY2RjZDdjZDRjZjFhY2M4Y2JmMzA3NTQ5MzkyMWNlMTIwMjk5MzRmMg%22\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 13:22:49] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 13:22:51] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"08e34d","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/08e34d","method":"GET"} []
[2017-10-23 13:22:52] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 13:22:52] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 13:23:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 13:24:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links%20%22Authorization:Bearer%20OThlMmY0ZDY2NDU2Yjg5MzU2NmYzZWMzY2RjZDdjZDRjZjFhY2M4Y2JmMzA3NTQ5MzkyMWNlMTIwMjk5MzRmMg%22"" at C:\wamp\www\comptabli\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links%20%22Authorization:Bearer%20OThlMmY0ZDY2NDU2Yjg5MzU2NmYzZWMzY2RjZDdjZDRjZjFhY2M4Y2JmMzA3NTQ5MzkyMWNlMTIwMjk5MzRmMg%22\" at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:123, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 13:24:07] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 13:24:10] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"1c41d8","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/1c41d8","method":"GET"} []
[2017-10-23 13:24:11] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 13:24:11] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 13:29:58] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-23 13:29:59] doctrine.DEBUG: SELECT t0.token AS token_1, t0.expires_at AS expires_at_2, t0.scope AS scope_3, t0.id AS id_4, t0.client_id AS client_id_5, t0.user_id AS user_id_6 FROM oauth2_access_tokens t0 WHERE t0.token = ? LIMIT 1 ["OThlMmY0ZDY2NDU2Yjg5MzU2Nm [...]"] []
[2017-10-23 13:29:59] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.id = ? [1] []
[2017-10-23 17:11:06] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-23 17:11:10] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 17:11:10] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 17:11:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /getDemos"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /getDemos\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 17:11:24] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 17:11:27] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"1672c1","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/1672c1","method":"GET"} []
[2017-10-23 17:11:27] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 17:11:27] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 17:12:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api_demos"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api_demos\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 17:12:08] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 17:12:10] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"f82b80","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/f82b80","method":"GET"} []
[2017-10-23 17:12:11] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 17:12:11] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 17:13:03] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/app_dev.php/","method":"GET"} []
[2017-10-23 17:13:03] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 17:13:03] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 17:13:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /index"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 17:13:16] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 17:13:18] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"bcd8b2","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/bcd8b2","method":"GET"} []
[2017-10-23 17:13:18] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 17:13:18] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 17:13:31] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api_rest"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api_rest\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 17:13:39] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 17:13:40] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"9ed9c4","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/9ed9c4","method":"GET"} []
[2017-10-23 17:13:41] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 17:13:41] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-23 17:13:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api_demos"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api_demos\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-23 17:13:52] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-23 17:13:54] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"f7c330","_route":"_wdt"},"request_uri":"http://localhost:8000/_wdt/f7c330","method":"GET"} []
[2017-10-23 17:13:55] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-23 17:13:55] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:13:59] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"GET"} []
[2017-10-24 11:14:12] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"GET"} []
[2017-10-24 11:16:42] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-24 11:16:42] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:16:42] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:16:52] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:16:57] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:19:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links%20%22Authorization:Bearer%20MDFjZGI1MTg4MTk3YmEwOWJmMzA4NmRiMTgxNTM0ZDc1MGI3NDgzYjIwNmI3NGQ0NGE0YTQ5YTVhNmNlNDZhZQ%22"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links%20%22Authorization:Bearer%20MDFjZGI1MTg4MTk3YmEwOWJmMzA4NmRiMTgxNTM0ZDc1MGI3NDgzYjIwNmI3NGQ0NGE0YTQ5YTVhNmNlNDZhZQ%22\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:19:44] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:19:46] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"c650f8","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/c650f8","method":"GET"} []
[2017-10-24 11:19:47] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:19:47] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:22:17] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-24 11:22:17] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-24 11:22:18] php.CRITICAL: Fatal Error: Call to a member function loadUserByUsername() on a non-object {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function loadUserByUsername() on a non-object at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:161)"} []
[2017-10-24 11:22:18] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function loadUserByUsername() on a non-object" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 161 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function loadUserByUsername() on a non-object at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:161)"} []
[2017-10-24 11:22:21] console.DEBUG: Command "server:start" exited with code "1" {"command":"server:start","code":1} []
[2017-10-24 11:23:23] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-24 11:23:24] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:23:24] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:23:28] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-24 11:23:28] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-24 11:23:29] php.CRITICAL: Fatal Error: Call to a member function loadUserByUsername() on a non-object {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function loadUserByUsername() on a non-object at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:161)"} []
[2017-10-24 11:23:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function loadUserByUsername() on a non-object" at C:\wamp\www\comptabli\vendor\friendsofsymfony\oauth-server-bundle\Storage\OAuthStorage.php line 161 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function loadUserByUsername() on a non-object at C:\\wamp\\www\\comptabli\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php:161)"} []
[2017-10-24 11:23:29] console.DEBUG: Command "server:run" exited with code "1" {"command":"server:run","code":1} []
[2017-10-24 11:25:40] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:25:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /comtabli"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /comtabli\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:25:57] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-24 11:25:57] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:25:58] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:26:49] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-24 11:26:50] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:26:50] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:26:59] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-24 11:27:00] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-24 11:27:00] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.username_canonical = ? LIMIT 1 ["admin"] []
[2017-10-24 11:27:00] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-24 11:27:01] doctrine.DEBUG: INSERT INTO oauth2_access_tokens (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"MWEyZDEyZDY1Nzg4NTkxOGM1Yj [...]","2":1508840820,"3":null,"4":1,"5":1} []
[2017-10-24 11:27:01] doctrine.DEBUG: "COMMIT" [] []
[2017-10-24 11:27:01] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-24 11:27:01] doctrine.DEBUG: INSERT INTO oauth2_refresh_tokens (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"ZmQ2ODVlZTI3MGQzOTQwOGUxMD [...]","2":1510046821,"3":null,"4":1,"5":1} []
[2017-10-24 11:27:01] doctrine.DEBUG: "COMMIT" [] []
[2017-10-24 11:28:18] request.INFO: Matched route "nelmio_api_doc_index". {"route":"nelmio_api_doc_index","route_parameters":{"_controller":"Nelmio\\ApiDocBundle\\Controller\\ApiDocController::indexAction","view":"default","_route":"nelmio_api_doc_index"},"request_uri":"http://localhost:8000/api/doc","method":"GET"} []
[2017-10-24 11:28:18] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:28:19] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:32:13] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"GET"} []
[2017-10-24 11:32:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /demo"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /demo\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:32:51] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:33:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /demo%20%22Authorization:Bearer%20MWEyZDEyZDY1Nzg4NTkxOGM1YjRhMWZkZGQ3MGM0YTkwNTI2OGFhYmEwMWEM2I4ZGQ1MGRmMzdiZjFmYzQwZQ%22"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /demo%20%22Authorization:Bearer%20MWEyZDEyZDY1Nzg4NTkxOGM1YjRhMWZkZGQ3MGM0YTkwNTI2OGFhYmEwMWEM2I4ZGQ1MGRmMzdiZjFmYzQwZQ%22\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:33:21] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:33:23] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"9fa84b","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/9fa84b","method":"GET"} []
[2017-10-24 11:33:24] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:33:24] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:38:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /demo"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /demo\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:38:13] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:38:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /Demo"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /Demo\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:38:34] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:38:48] request.INFO: Matched route "nelmio_api_doc_index". {"route":"nelmio_api_doc_index","route_parameters":{"_controller":"Nelmio\\ApiDocBundle\\Controller\\ApiDocController::indexAction","view":"default","_route":"nelmio_api_doc_index"},"request_uri":"http://localhost:8000/app_dev.php/api/doc","method":"GET"} []
[2017-10-24 11:38:49] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:38:49] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:40:11] request.INFO: Matched route "nelmio_api_doc_index". {"route":"nelmio_api_doc_index","route_parameters":{"_controller":"Nelmio\\ApiDocBundle\\Controller\\ApiDocController::indexAction","view":"default","_route":"nelmio_api_doc_index"},"request_uri":"http://localhost:8000/app_dev.php/api/doc","method":"GET"} []
[2017-10-24 11:40:12] doctrine.DEBUG: SELECT t0.token AS token_1, t0.expires_at AS expires_at_2, t0.scope AS scope_3, t0.id AS id_4, t0.client_id AS client_id_5, t0.user_id AS user_id_6 FROM oauth2_access_tokens t0 WHERE t0.token = ? LIMIT 1 ["MDFjZGI1MTg4MTk3YmEwOWJmMz [...]"] []
[2017-10-24 11:40:25] request.INFO: Matched route "nelmio_api_doc_index". {"route":"nelmio_api_doc_index","route_parameters":{"_controller":"Nelmio\\ApiDocBundle\\Controller\\ApiDocController::indexAction","view":"default","_route":"nelmio_api_doc_index"},"request_uri":"http://localhost:8000/app_dev.php/api/doc","method":"GET"} []
[2017-10-24 11:40:26] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:40:26] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:40:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /demo"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /demo\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:40:44] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:42:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /links"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /links\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:42:26] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 11:45:30] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/?client_id=1_3bcbxd9e24g0gk4swg0kwgcwg4o8k8g4g888kwc44gcc0gwwk4&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code&scope=&state=10189056","method":"GET"} []
[2017-10-24 11:45:31] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:45:31] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:45:39] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/?client_id=1_3bcbxd9e24g0gk4swg0kwgcwg4o8k8g4g888kwc44gcc0gwwk4&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code&scope=&state=10189059","method":"GET"} []
[2017-10-24 11:45:39] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-24 11:45:39] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-24 11:45:51] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-24 11:45:52] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-24 11:45:57] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-24 11:45:58] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-24 11:46:21] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-24 11:46:21] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-24 11:47:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /demo"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /demo\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:137)"} []
[2017-10-24 11:47:48] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-24 13:45:23] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-25 15:38:14] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig.php\",\"line\":120,\"trace\":[{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-25 15:39:06] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::indexAction","_route":"homepage"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2017-10-25 15:39:16] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-25 15:39:16] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-25 15:44:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/demo"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/demo\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:160)"} []
[2017-10-25 15:45:13] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-25 15:45:15] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"6934da","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/6934da","method":"GET"} []
[2017-10-25 15:45:16] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-25 15:45:16] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-25 15:45:28] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/demos"" at C:\wamp\www\comptabli\var\cache\dev\classes.php line 3754 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/demos\" at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\classes.php:3754, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\wamp\\www\\comptabli\\var\\cache\\dev\\appDevDebugProjectContainerUrlMatcher.php:160)"} []
[2017-10-25 15:45:34] php.DEBUG: Warning: stream_context_get_params(): Invalid stream/context parameter {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Caster\\\\ResourceCaster.php\",\"line\":53,\"trace\":[{\"function\":\"handleError\",\"class\":\"Symfony\\\\Component\\\\Debug\\\\ErrorHandler\",\"type\":\"->\"},{\"file\":\"C:\\\\wamp\\\\www\\\\comptabli\\\\vendor\\\\symfony\\\\symfony\\\\src\\\\Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner.php\",\"line\":205,\"function\":\"call_user_func\"},{\"function\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\{closure}\",\"class\":\"Symfony\\\\Component\\\\VarDumper\\\\Cloner\\\\AbstractCloner\",\"type\":\"->\"}],\"count\":1})"} []
[2017-10-25 15:45:35] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e19270","_route":"_wdt"},"request_uri":"http://localhost:8000/app_dev.php/_wdt/e19270","method":"GET"} []
[2017-10-25 15:45:36] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-25 15:45:36] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-25 15:45:59] request.INFO: Matched route "get_demos". {"route":"get_demos","route_parameters":{"_controller":"ApiBundle\\Controller\\DemoController::getDemosAction","_format":"json","_route":"get_demos"},"request_uri":"http://localhost:8000/app_dev.php/api/api/demos","method":"GET"} []
[2017-10-25 15:45:59] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at C:\\wamp\\www\\comptabli\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:53)"} []
[2017-10-25 15:46:00] security.DEBUG: Calling Authentication entry point. [] []
[2017-10-25 15:46:59] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-25 15:47:00] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-25 15:47:00] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.username_canonical = ? LIMIT 1 ["admin"] []
[2017-10-25 15:47:00] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-25 15:47:00] doctrine.DEBUG: INSERT INTO oauth2_access_tokens (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"OTQ5ZjY5NzkyODkyNzUzMDI4ZT [...]","2":1508942820,"3":null,"4":1,"5":1} []
[2017-10-25 15:47:01] doctrine.DEBUG: "COMMIT" [] []
[2017-10-25 15:47:01] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-25 15:47:01] doctrine.DEBUG: INSERT INTO oauth2_refresh_tokens (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"YTc5MGU0ZGZiNzBmYTVjNzIwOD [...]","2":1510148821,"3":null,"4":1,"5":1} []
[2017-10-25 15:47:01] doctrine.DEBUG: "COMMIT" [] []
[2017-10-25 15:51:29] request.INFO: Matched route "get_demos". {"route":"get_demos","route_parameters":{"_controller":"ApiBundle\\Controller\\DemoController::getDemosAction","_format":"json","_route":"get_demos"},"request_uri":"http://localhost:8000/app_dev.php/api/api/demos","method":"GET"} []
[2017-10-25 15:51:30] doctrine.DEBUG: SELECT t0.token AS token_1, t0.expires_at AS expires_at_2, t0.scope AS scope_3, t0.id AS id_4, t0.client_id AS client_id_5, t0.user_id AS user_id_6 FROM oauth2_access_tokens t0 WHERE t0.token = ? LIMIT 1 ["MWEyZDEyZDY1Nzg4NTkxOGM1Yj [...]"] []
[2017-10-25 15:51:41] request.INFO: Matched route "fos_oauth_server_token". {"route":"fos_oauth_server_token","route_parameters":{"_controller":"fos_oauth_server.controller.token:tokenAction","_route":"fos_oauth_server_token"},"request_uri":"http://localhost:8000/app_dev.php/oauth/v2/token","method":"POST"} []
[2017-10-25 15:51:42] doctrine.DEBUG: SELECT t0.random_id AS random_id_1, t0.redirect_uris AS redirect_uris_2, t0.secret AS secret_3, t0.allowed_grant_types AS allowed_grant_types_4, t0.id AS id_5 FROM oauth2_clients t0 WHERE t0.id = ? AND t0.random_id = ? LIMIT 1 ["1","3bcbxd9e24g0gk4swg0kwgcwg4 [...]"] []
[2017-10-25 15:51:42] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.username_canonical = ? LIMIT 1 ["admin"] []
[2017-10-25 15:51:42] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-25 15:51:42] doctrine.DEBUG: INSERT INTO oauth2_access_tokens (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"NDZhYTA5ZWNmNzNlNWFjODBhNG [...]","2":1508943102,"3":null,"4":1,"5":1} []
[2017-10-25 15:51:42] doctrine.DEBUG: "COMMIT" [] []
[2017-10-25 15:51:42] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-10-25 15:51:42] doctrine.DEBUG: INSERT INTO oauth2_refresh_tokens (token, expires_at, scope, client_id, user_id) VALUES (?, ?, ?, ?, ?) {"1":"NjFhNWZiZGE2MDQzYzU2NjMxM2 [...]","2":1510149102,"3":null,"4":1,"5":1} []
[2017-10-25 15:51:42] doctrine.DEBUG: "COMMIT" [] []
[2017-10-25 15:53:58] request.INFO: Matched route "get_demos". {"route":"get_demos","route_parameters":{"_controller":"ApiBundle\\Controller\\DemoController::getDemosAction","_format":"json","_route":"get_demos"},"request_uri":"http://localhost:8000/app_dev.php/api/api/demos","method":"GET"} []
[2017-10-25 15:53:58] doctrine.DEBUG: SELECT t0.token AS token_1, t0.expires_at AS expires_at_2, t0.scope AS scope_3, t0.id AS id_4, t0.client_id AS client_id_5, t0.user_id AS user_id_6 FROM oauth2_access_tokens t0 WHERE t0.token = ? LIMIT 1 ["NDZhYTA5ZWNmNzNlNWFjODBhNG [...]"] []
[2017-10-25 15:53:58] doctrine.DEBUG: SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.id = ? [1] []
